# Generated by Django 4.2.1 on 2023-05-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('start_time', models.TimeField()),
            ],
            options={
                'db_table': 'classrooms',
            },
        ),
        migrations.CreateModel(
            name='ExamenFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_fecha', models.DateTimeField()),
                ('curso', models.CharField(max_length=30)),
                ('evaluador', models.CharField(max_length=50)),
                ('duracion_exam', models.IntegerField()),
                ('num_preguntas', models.IntegerField()),
                ('puntaje_total', models.IntegerField()),
            ],
            options={
                'db_table': 'examen_final',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_fecha', models.DateTimeField()),
                ('curso', models.CharField(max_length=30)),
                ('evaluador', models.CharField(max_length=50)),
                ('tema_proyecto', models.CharField(max_length=100)),
                ('num_grupos', models.IntegerField()),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('born_date', models.DateField()),
                ('salary', models.FloatField(default=0.0)),
                ('rating', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('born_date', models.DateField()),
                ('grade_lab', models.FloatField(default=0.0)),
                ('grade_exam', models.FloatField(default=0.0)),
                ('grade_final', models.FloatField(default=0.0)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.classroom')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.teacher'),
        ),
        migrations.CreateModel(
            name='ProyectoProxy',
            fields=[
            ],
            options={
                'ordering': ['tema_proyecto'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administracion.proyecto',),
        ),
        migrations.CreateModel(
            name='StudentProxy',
            fields=[
            ],
            options={
                'ordering': ['-id'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administracion.student',),
        ),
        migrations.CreateModel(
            name='TeacherProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administracion.teacher',),
        ),
    ]
