# Generated by Django 4.2.1 on 2023-05-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_studentproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administracion.teacher',),
        ),
    ]
